azure:
  activedirectory:
    tenant-id: a3024586-211d-4ae3-a913-c5849a46bebc
    client-id: e0a6863c-08a1-4f03-a8f1-52581e844f74
    client-secret: 6V8ea-hgAYZw1jr_UFF-I-6sxR1jViC~41
    user-group:
      allowed-group-names: group2